services:
  ai-generated-tweet-to-kafka-service:
    image: ${GROUP_ID}/ai.generated.tweet.to.kafka.service:${SERVICE_VERSION:-latest}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/ai-generated-tweet-to-kafka-service/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=ai-generated-tweet-to-kafka-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_AI_OLLAMA_BASE-URL=http://host.docker.internal:11434"
      - "SPRING_AI_OLLAMA_CHAT_OPTIONS_TIMEOUT=300s"
      - "SPRING_AI_RETRY_MAX-ATTEMPTS=1"
    networks:
      - ${GLOBAL_NETWORK:-services}